#████████╗██╗███╗░░░███╗░█████╗░░██████╗████████╗██████╗░███████╗░█████╗░███╗░░░███╗
#╚══██╔══╝██║████╗░████║██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔══██╗████╗░████║
#░░░██║░░░██║██╔████╔██║███████║╚█████╗░░░░██║░░░██████╔╝█████╗░░███████║██╔████╔██║
#░░░██║░░░██║██║╚██╔╝██║██╔══██║░╚═══██╗░░░██║░░░██╔══██╗██╔══╝░░██╔══██║██║╚██╔╝██║
#░░░██║░░░██║██║░╚═╝░██║██║░░██║██████╔╝░░░██║░░░██║░░██║███████╗██║░░██║██║░╚═╝░██║
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#pls use \n to indent
#
messages:
  stream: "&f&m----------------------------------\n&r&5&lСтример &e%player% &fначал стримить!\n&c&l--> &b%link%\n&f&m----------------------------------\n"
  noperm: "&cТолько &5&lСтример &cможет использовать эту команду!"
  strstart: "&aВы оповестили сервер о вашем стриме!"
  noargs: "&cВы не ввели ссылку на стрим! Правильно так - /stream <ссылка>"
  not_player: "&cЭту команду нельзя использовать через командный блок или консоль!"
#
#thanks for use my plugin <3